### ISSUE TITLE
Suggestions for improvement

### ISSUE THREAD

**Issue by netodeolino** [henricker/college-notification-discord#12]
Hello,
Your project is really interesting and that's why I'm suggesting some very simple improvements that can help the project to be used by more people. Furthermore, other universities also have Moodle and SIGAA and their students can use your project :)

#### The first one is to create env variable for these email address:

https://github.com/henricker/college-notification-discord/blob/9841ed15b4f48aa169db4232a5a30c642c5f2cd9/src/application/services/mail-watcher.service.ts#L37
https://github.com/henricker/college-notification-discord/blob/9841ed15b4f48aa169db4232a5a30c642c5f2cd9/src/application/services/mail-watcher.service.ts#L38

#### Also create const variable for these "magic" numbers:

https://github.com/henricker/college-notification-discord/blob/9841ed15b4f48aa169db4232a5a30c642c5f2cd9/src/index.ts#L22
https://github.com/henricker/college-notification-discord/blob/9841ed15b4f48aa169db4232a5a30c642c5f2cd9/src/infra/services/fetch-mail.service.ts#L137
https://github.com/henricker/college-notification-discord/blob/9841ed15b4f48aa169db4232a5a30c642c5f2cd9/src/infra/services/discord.service.ts#L33

#### Also create a README file to help other developers and users to use the app. Overall, awesome project and code :)

**Comment by henricker** [comment]
Thanks for your tips!, I will definitely make these adjustments you said!.

**Comment by henricker** [comment]
I added the improvement changes!, thanks!
